# Generated by Django 3.1.7 on 2021-03-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Название продукта')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('product_photo', models.ImageField(upload_to='')),
                ('categorie', models.CharField(choices=[('Laptops', 'Laptops'), ('Smarphones', 'Smarphones')], default='Laptops', max_length=100, verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('product_name',),
            },
        ),
    ]
