# Generated by Django 3.1.7 on 2021-03-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categorie',
            field=models.CharField(choices=[('Laptops', 'Laptops'), ('Smarphones', 'Smarphones')], default='Laptops', max_length=50, verbose_name='Категории'),
        ),
    ]
